# Supabase project configuration
project_id = "qvppvstgconmzzjsryna"

[auth]
enabled = true

[functions.offer-lookup]
verify_jwt = false

[functions.offer-respond]
verify_jwt = false

[functions.expire-offers]
verify_jwt = false

[functions.debug-secrets]
verify_jwt = false

[functions.partner-import]
verify_jwt = true

[functions.test-partner-import]
verify_jwt = false

[functions.backfill-partner-clients]
verify_jwt = false

[functions.google-sheets-preview]
verify_jwt = true

[functions.seed-scheduling-data-v2]
verify_jwt = false

[functions.send-survey-reminders]
verify_jwt = false

[functions.survey-lookup]
verify_jwt = false

[functions.survey-upload]
verify_jwt = false

[functions.admin-delete-order]
verify_jwt = true

[functions.quote-snapshot-save]
verify_jwt = true

[functions.admin-set-password]
verify_jwt = true

[functions.send-user-invite]
verify_jwt = true

[functions.admin-create-engineer-user]
verify_jwt = true