project_id = "qvppvstgconmzzjsryna"

[functions.client-accept-quote]
verify_jwt = false

[functions.import-engineers]
verify_jwt = false

[functions.admin-create-client]
verify_jwt = false

[functions.admin-create-client-v2]
verify_jwt = false

[functions.seed-scheduling-data]
verify_jwt = true

[functions.clear-seed-data]
verify_jwt = true