# Supabase project configuration
project_id = "qvppvstgconmzzjsryna"

[auth]
enabled = true

[functions.offer-lookup]
verify_jwt = false

[functions.offer-respond]
verify_jwt = false

[functions.expire-offers]
verify_jwt = false

[functions.debug-secrets]
verify_jwt = false

[functions.partner-import]
verify_jwt = true

[functions.test-partner-import]
verify_jwt = false