
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { QuoteDetailView } from '@/components/QuoteDetailView';
import { BrandPage, BrandContainer, BrandLoading } from '@/components/brand';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

interface Quote {
  id: string;
  quote_number: string;
  total_cost: number;
  materials_cost: number;
  install_cost: number;
  extras_cost: number;
  status: string;
  created_at: string;
  expires_at: string | null;
  product_details: string;
  special_instructions: string | null;
  warranty_period: string | null;
  includes_installation: boolean;
  notes: string | null;
  is_shareable: boolean;
  share_token: string | null;
  // Optional fields that might not exist in database
  room_info?: string | null;
  range?: string | null;
  finish?: string | null;
  deposit_required?: number;
  client: {
    id: string;
    full_name: string;
    email: string;
    phone: string | null;
    address: string | null;
  };
}

export default function AdminQuoteDetail() {
  const { id: quoteId } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [quote, setQuote] = useState<Quote | null>(null);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    if (!quoteId) {
      navigate('/admin/quotes');
      return;
    }
    fetchQuote();
  }, [quoteId]);

  const fetchQuote = async () => {
    try {
      const { data, error } = await supabase
        .from('quotes')
        .select(`
          *,
          client:clients(
            id,
            full_name,
            email,
            phone,
            address
          )
        `)
        .eq('id', quoteId)
        .single();

      if (error) throw error;
      
      // Transform the data to match our interface, providing defaults for missing fields
      const transformedQuote = {
        ...data,
        room_info: null,
        range: null,
        finish: null,
        deposit_required: data.total_cost * 0.25, // Default to 25% of total cost
      };
      
      setQuote(transformedQuote);
    } catch (error) {
      console.error('Error fetching quote:', error);
      toast({
        title: "Error",
        description: "Failed to load quote details",
        variant: "destructive",
      });
      navigate('/admin/quotes');
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    navigate('/admin/quotes');
  };

  const handleRejectQuote = async (quoteId: string) => {
    try {
      // First check if there's an associated order
      const { data: orderData } = await supabase
        .from('orders')
        .select('id')
        .eq('quote_id', quoteId)
        .maybeSingle();

      // Update quote status to rejected
      const { error: updateError } = await supabase
        .from('quotes')
        .update({ 
          status: 'rejected',
          accepted_at: null
        })
        .eq('id', quoteId);

      if (updateError) throw updateError;

      // Delete associated order if it exists
      if (orderData) {
        const { error: deleteError } = await supabase
          .from('orders')
          .delete()
          .eq('quote_id', quoteId);

        if (deleteError) throw deleteError;
      }

      toast({
        title: "Quote Rejected",
        description: orderData ? "Quote rejected and associated order deleted." : "Quote rejected successfully.",
      });

      // Refresh quote data
      fetchQuote();

    } catch (error) {
      console.error('Error rejecting quote:', error);
      toast({
        title: "Error",
        description: "Failed to reject quote",
        variant: "destructive",
      });
    }
  };

  const handleAcceptQuote = async (quoteId: string) => {
    try {
      // Check if order already exists for this quote
      const { data: existingOrder } = await supabase
        .from('orders')
        .select('id')
        .eq('quote_id', quoteId)
        .maybeSingle();

      // Update quote status to accepted
      const { error: updateError } = await supabase
        .from('quotes')
        .update({ 
          status: 'accepted',
          accepted_at: new Date().toISOString()
        })
        .eq('id', quoteId);

      if (updateError) throw updateError;

      let order = existingOrder;

      // Only create order if one doesn't exist
      if (!existingOrder && quote) {
        // Create order from accepted quote
        const { data: newOrder, error: orderError } = await supabase
          .from('orders')
          .insert({
            order_number: '', // Will be auto-generated by trigger
            client_id: quote.client.id,
            quote_id: quote.id,
            total_amount: quote.total_cost,
            deposit_amount: quote.deposit_required || (quote.total_cost * 0.25),
            job_address: quote.client.address || null,
            internal_install_notes: quote.room_info || null
          })
          .select()
          .single();

        if (orderError) throw orderError;
        order = newOrder;
      }

      toast({
        title: "Quote Accepted!",
        description: existingOrder ? "Quote status updated successfully." : "Order has been created successfully. Redirecting...",
      });

      // Refresh quote data
      fetchQuote();

      // Redirect to order details page if new order was created
      if (!existingOrder && order) {
        setTimeout(() => {
          navigate(`/orders/${order.id}`);
        }, 1500);
      }

    } catch (error) {
      console.error('Error accepting quote:', error);
      toast({
        title: "Error",
        description: "Failed to accept quote",
        variant: "destructive",
      });
    }
  };

  if (loading) {
    return <BrandLoading />;
  }

  if (!quote) {
    return (
      <BrandPage>
        <BrandContainer>
          <div className="text-center py-12">
            <h2 className="text-xl font-semibold mb-4">Quote not found</h2>
            <Button onClick={handleBack} variant="outline">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Quotes
            </Button>
          </div>
        </BrandContainer>
      </BrandPage>
    );
  }

  return (
    <BrandPage>
      <BrandContainer>
        <QuoteDetailView 
          quote={{
            ...quote,
            deposit_required: quote.deposit_required || quote.total_cost * 0.25
          }} 
          onBack={handleBack}
          onAccept={handleAcceptQuote}
          onReject={handleRejectQuote}
        />
      </BrandContainer>
    </BrandPage>
  );
}
